language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - build-tools-25.0.3
  - android-23
  - android-25
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+ 

before_install: sh build.sh && cd ftc_app

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
 
cache:
 directories:
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
